### ISSUE TITLE
justgifit.com site down!

### ISSUE THREAD

**Issue by sharpguru** [dustinschultz/just-gif-it-autoconfigure#1]
![image](https://user-images.githubusercontent.com/1870384/41015803-be987274-6900-11e8-987c-d68688aafe19.png)

**Comment by dustinschultz** [comment]
Hi Brian! 

There shouldn't be any content in the course that relies on justgifit.com. Are you having issues related to it?

Thanks,
Dustin

**Comment by sharpguru** [comment]
Nah, it's just that it was mentioned in the course and I saw the dns name exists but isn't working. Thought you might get a kick out of it. No worries, enjoying the course though!

Thanks,
-Brian

**Comment by dustinschultz** [comment]
Haha! I should put some sort of "easter egg" on the site! 

Glad you're enjoying the course.
